# AGENTS.md — {{SERVICE_NAME}} MCP

Go MCP template with hexagonal architecture, `cobra` + `viper`, DI, and tool handlers grouped by concept.

## Mandatory Skills

Before making changes in this repository, load and apply these local skills:

- `.codex/skills/clean-code`
- `.codex/skills/golang-pro`
- `.codex/skills/sql-pro`
- `.codex/skills/tdd-workflows-tdd-cycle`
- `.codex/skills/tdd-workflows-tdd-red`
- `.codex/skills/tdd-workflows-tdd-green`
- `.codex/skills/tdd-workflows-tdd-refactor`

Notes:

- The scaffold reads these skills from `template/skills/` in this repository and copies them into `.codex/skills/` in the generated project.
- `.claude/skills` and `.opencode/skills` are symlinks to `.codex/skills` in the generated project.

## Structure

```text
{{SERVICE_NAME}}/
├── cmd/server/main.go
├── mcp/
│   ├── application/
│   └── domain/
├── platform/
│   ├── config/
│   ├── di/
│   ├── mcp/
│   │   ├── commands/
│   │   ├── server/
│   │   ├── tools/
│   │   └── hello/
│   └── openai/
└── shared/
    ├── ai/domain/
    └── config/domain/
```

## MCP Convention

- Entry point: `cmd/server/main.go`.
- Command-line parameters are managed with `cobra` and bound to `viper`.
- MCP server wiring lives in `platform/mcp/server/server.go`.
- Tool definitions live in `platform/mcp/tools/` and are registered from the command runner.
- Default transport: `stdio`.

Included example:

- Tool `hello_world` with required `name` argument.

## Adding a New MCP Tool

1. Create a domain port under `mcp/domain/<feature>/` if business logic is needed.
2. Add the use case in `mcp/application/<feature>/`.
3. Implement infrastructure adapters in `platform/mcp/<feature>/`.
4. Create the tool definition and handler in `platform/mcp/tools/<feature>.go`.
5. Register dependencies in `platform/di/container.go`.
6. Register the tool in the command runner before server startup.

## Layer Dependencies

```text
platform -> shared + mcp/application + mcp/domain
mcp/application -> mcp/domain
cmd -> platform + shared
```

Do not allow `shared` or `mcp/domain` to import `platform`.

## Service and Repository Size Rule

- Do not create giant monolithic services or repositories.
- Split responsibilities into multiple focused `.go` files, following `clean-code` (SRP, small units, clear naming).
- Prefer composition of small components over one large file handling everything.

## First-Level Business Entities

If a specific domain appears (example: `post`), place it at project root:

```text
post/
├── application/
└── domain/
```

This is only a structural example; no `post` boilerplate is generated by default.

## Checklist

- [ ] New tools are registered in startup wiring.
- [ ] Flags are bound via `viper` and support env overrides.
- [ ] No `platform` imports inside `shared` or `mcp/domain`.
- [ ] OpenAI provider config is read via config repository.
- [ ] `go test ./...` and `go vet ./...` pass.
